//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUEjercicio
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Alumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumno()
        {
            this.Matriculas = new HashSet<Matricula>();
        }

        [ScaffoldColumn(false)]
        public int idalumno { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Los nombres son requeridos"), MaxLength(55)]
        [Display(Name = "Nombres")]
        public string nombres { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Los apellidos son requeridos"), MaxLength(55)]
        [Display(Name = "Apellidos")]
        public string apellidos { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "La cedula es requerida"), MaxLength(15)]
        [Display(Name = "Cédula")]
        public string cedula { get; set; }

        [Display(Name = "Fecha de nacimiento")]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }

        [DataType(DataType.Text)]
        [Display(Name = "Lugar de nacimiento")]
        public string lugar_nacimiento { get; set; }

        [Display(Name = "Sexo")]
        public string sexo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Matricula> Matriculas { get; set; }
        public override string ToString()
        {
            return nombres + " " + apellidos;
        }
    }
}
