
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BEUEjercicio
{

using System;
    using System.Collections.Generic;
    
public partial class Beca
{

    public int idbeca { get; set; }

    public string solicitante { get; set; }

    public string tipo_beca { get; set; }

    public string semestre { get; set; }

    public Nullable<System.DateTime> fecha_pedido { get; set; }

    public Nullable<int> promedio_general { get; set; }

}

}
