//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUEjercicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maquinaria
    {
        public int idmaquinaria { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fecha_adquisicion { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> porcentaje_depreciacion { get; set; }
    }
}
