//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUEjercicio
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Materia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materia()
        {
            this.Matriculas = new HashSet<Matricula>();
        }

        [ScaffoldColumn(false)]
        public int idmateria { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El nombre es requerido"), MaxLength(55)]
        [Display(Name = "Nombre")]
        public string nombre { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El NRC es requerido"), MaxLength(5)]
        [Display(Name = "NRC")]
        public string nrc { get; set; }

        [Range(2,10, ErrorMessage = "El número de créditos debe ser entre 2 y 10")]
        [Required(ErrorMessage = "El NRC es requerido")]
        [Display(Name = "Créditos")]
        public Nullable<short> creditos { get; set; }

        [Required(ErrorMessage = "El área es requerida")]
        public Nullable<int> idarea { get; set; }
                
        public virtual Area Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Matricula> Matriculas { get; set; }

        public override string ToString()
        {
            return this.nrc + " " + this.nombre;
        }


    }
}
